default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: prereq_data_dev


test:
  <<: *default
  database: prereq_data_test

something:
  <<: *default
  database: prereq_data_something
